### ISSUE TITLE
error when try to run sample code

### ISSUE THREAD

**Issue by Gr3gorywolf** [henrikvik/node-vigem#1]
when i try to run the sample code node trows me the following error
node_modules\bindings\bindings.js:121
        throw e;
        ^

Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:730:18)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at bindings (C:\Aplicaciones web\Chroma controller\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\Aplicaciones web\Chroma controller\node_modules\node-vigem\addon.js:1:94)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)

pls help me i really want to use this lib

**Comment by henrikvik** [comment]
Hello! Sorry for the late reply, Ill look into it!
In the mean time you could try [vigem-interface](https://github.com/henrikvik/vigem-interface/releases) it is something that I created because this lib kept breaking between node versions :). Feel free to ask anything related to these two repos in this issue.

```js
var execFile= require('child_process').execFile;
var child = execFile('vigem-interface.exe');

child.stdin.setEncoding('utf-8');
child.stdin.write("@ A+ X+ D3 L6 L+\n");
// write always have to end with ' ' or '\n' or the last input wont be parsed
``` 
I have not tested this example and cant do that right now, it might need some modification to run. I will test and make a working example in the evening.
